
version: '2'

services:

  gatling:
    image: vbaer/flaskout
    volumes:
      - ./user-files:/opt/gatling/user-files
      - ./user-files/:/app/user-files/
    ports:
      - "8080:8080"
    environment:
      - Jsonpoint=http://192.168.2.77:1010/test/conf/matrix/test
      - Url_Matrix=http://192.168.2.77:8008

