version: '2'

services:

  gatling:
    image: vbaer/flask
    volumes:
      - ./user-files:/opt/gatling/user-files
      - ./user-files/simulations:/app/user-files/
    ports:
      - "8080:8080"
    environment:
      - Jsonpoint=http://146.148.86.153:5050/test.json
