apiVersion: v1
kind: ReplicationController
metadata:
  name: matrix
spec:
  replicas: 2
  selector:
    name: matrix
  template:
    metadata:
      labels:
        name: matrix
    spec:
      containers:
      - image: vbaer/kubematrix
        name: matrix
        volumeMounts:
          # name must match the volume name below
          - name: nfs
            mountPath: "/tmp/data"
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: data
